### ISSUE TITLE
[BUG] Erro 500 ao enviar requisição com problema

### ISSUE THREAD

**Issue by rodrigosv91** [AppMorada/MoradaApp.registryApi#98]
**Descreva o bug**
Recebi status code 500 ao enviar para o servidor uma requisição com uma aspas dupla extra

**Como reproduzir**
Passos para detectar o bug:
1. No postman envie um requisição do tipo post para "/login" na api
2. Preencha o corpo da requisição com:
{
  "email": "emailValido@email.com",
  "password": "123456789Ab@"
  "
}
3. Receba o erro: {"statusCode":500,"message":"Erro interno do servidor"}

**Comportamento esperado**
Esperava-se um erro da família 400*

**Prints**
![image](https://github.com/AppMorada/MoradaApp.registryApi/assets/8875989/9a51d0c0-a68f-48a9-999b-024c5676597d)

**Informações do hardware:**
 - OS: Windows
 - Navegador: N/A
 - Versão: 11

**Comment by NicolasCBV** [comment]
Erro já identificado e corrigido na imagem de pré-lançamento 'moradaapp/registry-api-alpha', basta aguardar o deploy do sistema em nuvem, ou realizar a execução do sistema localmente pelo diretório /example

**Comment by NicolasCBV** [comment]
Correções implantadas com sucesso no ambiente de desenvolvimento em nuvem, podendo ser validado por: [https://experimental-0-0-0---registryapi-7bv5li53oq-rj.a.run.app/](https://experimental-0-0-0---registryapi-7bv5li53oq-rj.a.run.app/)
